// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// แพ็กเก็ตข้อความข้าม FFI (mirror ของ `MessagePacket`)
class MessagePacketDto {
  final String id;
  final String sender;
  final String receiver;
  final Uint8List payload;
  final BigInt timestamp;
  final int ttl;
  final PayloadTagDto payloadTag;

  const MessagePacketDto({
    required this.id,
    required this.sender,
    required this.receiver,
    required this.payload,
    required this.timestamp,
    required this.ttl,
    required this.payloadTag,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      receiver.hashCode ^
      payload.hashCode ^
      timestamp.hashCode ^
      ttl.hashCode ^
      payloadTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessagePacketDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          receiver == other.receiver &&
          payload == other.payload &&
          timestamp == other.timestamp &&
          ttl == other.ttl &&
          payloadTag == other.payloadTag;
}

/// สถานะเครือข่ายจาก Flutter (`connectivity_plus` + BLE scan)
class NetworkStatusDto {
  final bool isInternetAvailable;
  final int activeBlePeersCount;

  const NetworkStatusDto({
    required this.isInternetAvailable,
    required this.activeBlePeersCount,
  });

  @override
  int get hashCode =>
      isInternetAvailable.hashCode ^ activeBlePeersCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkStatusDto &&
          runtimeType == other.runtimeType &&
          isInternetAvailable == other.isInternetAvailable &&
          activeBlePeersCount == other.activeBlePeersCount;
}

/// ประเภท payload (wire tag: Text=1, Image=2, Audio=3, Firmware=4, Ack=5)
enum PayloadTagDto { text, image, audio, firmware, ack }

/// ผลการ route ส่งกลับไปยัง Flutter
class RoutedPacketDto {
  final TransportTypeDto transport;
  final MessagePacketDto packet;

  const RoutedPacketDto({required this.transport, required this.packet});

  @override
  int get hashCode => transport.hashCode ^ packet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoutedPacketDto &&
          runtimeType == other.runtimeType &&
          transport == other.transport &&
          packet == other.packet;
}

/// การตั้งค่า Router จาก Flutter
class RouterConfigDto {
  final int dedupCapacity;
  final BigInt dedupTtlSecs;
  final int internetTtlReset;
  final int offlineQueueCapacity;
  final int eventChannelCapacity;
  final int incomingChannelCapacity;

  const RouterConfigDto({
    required this.dedupCapacity,
    required this.dedupTtlSecs,
    required this.internetTtlReset,
    required this.offlineQueueCapacity,
    required this.eventChannelCapacity,
    required this.incomingChannelCapacity,
  });

  @override
  int get hashCode =>
      dedupCapacity.hashCode ^
      dedupTtlSecs.hashCode ^
      internetTtlReset.hashCode ^
      offlineQueueCapacity.hashCode ^
      eventChannelCapacity.hashCode ^
      incomingChannelCapacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouterConfigDto &&
          runtimeType == other.runtimeType &&
          dedupCapacity == other.dedupCapacity &&
          dedupTtlSecs == other.dedupTtlSecs &&
          internetTtlReset == other.internetTtlReset &&
          offlineQueueCapacity == other.offlineQueueCapacity &&
          eventChannelCapacity == other.eventChannelCapacity &&
          incomingChannelCapacity == other.incomingChannelCapacity;
}

/// ช่องทางส่งข้อมูล (mirror ของ `TransportType`)
enum TransportTypeDto { internet, bluetoothMesh, offlineQueue }
