// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// เริ่ม Nostr identity (generate หรือ restore จาก secret hex) + เชื่อม relay pool
///
/// After connect, background task auto-ingests ResilNet envelopes into the hybrid router
/// (same dedup path as BLE / LoRa).
Future<NostrInitResultDto> initNostr({
  String? secretKeyHex,
  List<String>? relayUrls,
}) => ResilNetCore.instance.api.crateApiNostrApiInitNostr(
  secretKeyHex: secretKeyHex,
  relayUrls: relayUrls,
);

Future<NostrPoolStatusDto> getNostrStatus() =>
    ResilNetCore.instance.api.crateApiNostrApiGetNostrStatus();

Future<void> nostrReconnect() =>
    ResilNetCore.instance.api.crateApiNostrApiNostrReconnect();

/// Publish ResilNet envelope to Nostr relays (kind = direct | broadcast | health)
Future<String> nostrPublish({
  required ResilNetEnvelopeDto envelope,
  required String kind,
}) => ResilNetCore.instance.api.crateApiNostrApiNostrPublish(
  envelope: envelope,
  kind: kind,
);

/// Publish a routed MessagePacketDto as a Nostr direct/broadcast envelope
Future<String> nostrPublishPacket({required MessagePacketDto packet}) =>
    ResilNetCore.instance.api.crateApiNostrApiNostrPublishPacket(
      packet: packet,
    );

/// Flush offline queue: publish each queued packet to Nostr when online
Future<int> flushOfflineQueueToNostr() =>
    ResilNetCore.instance.api.crateApiNostrApiFlushOfflineQueueToNostr();

/// Convert a Nostr envelope into a MessagePacket and ingest through router dedup
Future<void> ingestNostrEnvelope({required ResilNetEnvelopeDto envelope}) =>
    ResilNetCore.instance.api.crateApiNostrApiIngestNostrEnvelope(
      envelope: envelope,
    );
