// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_router_error`

/// สร้าง `ResilNetRouter` และพร้อมรับคำสั่งจาก Flutter
Future<void> initRouter({required RouterConfigDto config}) =>
    ResilNetCore.instance.api.crateApiRouterApiInitRouter(config: config);

/// อัปเดตสถานะเครือข่ายจาก Flutter (`connectivity_plus` + BLE peer count)
Future<void> updateNetworkStatus({
  required bool isInternetAvailable,
  required int activeBlePeersCount,
}) => ResilNetCore.instance.api.crateApiRouterApiUpdateNetworkStatus(
  isInternetAvailable: isInternetAvailable,
  activeBlePeersCount: activeBlePeersCount,
);

/// อ่านสถานะเครือข่ายล่าสุดที่ router เก็บไว้
Future<NetworkStatusDto> getNetworkStatus() =>
    ResilNetCore.instance.api.crateApiRouterApiGetNetworkStatus();

/// ส่งออกแพ็กเก็ตผ่าน Hybrid State Machine (Internet → BLE → Offline Queue)
Future<RoutedPacketDto> routePacket({required MessagePacketDto packet}) =>
    ResilNetCore.instance.api.crateApiRouterApiRoutePacket(packet: packet);

/// รับแพ็กเก็ตขาเข้า — กรองซ้ำ LRU+TTL ก่อนส่งต่อ UI ผ่าน Stream
Future<void> ingestPacket({required MessagePacketDto packet}) =>
    ResilNetCore.instance.api.crateApiRouterApiIngestPacket(packet: packet);

/// จำนวนข้อความที่รอส่งใน offline queue
Future<int> offlineQueueLen() =>
    ResilNetCore.instance.api.crateApiRouterApiOfflineQueueLen();

/// สร้าง Stream ข้อความเข้าแบบ real-time ไปยัง Flutter UI
///
/// ฟัง `RouterEvent::IncomingMessage` จาก broadcast channel — เรียกซ้ำได้เมื่อแอป resume
/// (abort task เก่าแล้วสมัครใหม่ ไม่ต้อง take MPSC receiver ครั้งเดียว)
Stream<MessagePacketDto> subscribeIncomingMessages() =>
    ResilNetCore.instance.api.crateApiRouterApiSubscribeIncomingMessages();

/// ตรวจว่า router ถูก init แล้วหรือยัง
bool isRouterInitialized() =>
    ResilNetCore.instance.api.crateApiRouterApiIsRouterInitialized();

/// กรอง chunk frame ซ้ำระหว่าง reassembly (audio/firmware binary streams)
bool checkChunkDedup({required int msgId, required int chunkIndex}) =>
    ResilNetCore.instance.api.crateApiRouterApiCheckChunkDedup(
      msgId: msgId,
      chunkIndex: chunkIndex,
    );

/// ล้าง chunk dedup cache เมื่อประกอบ binary stream เสร็จ
void clearChunkStream({required int msgId}) =>
    ResilNetCore.instance.api.crateApiRouterApiClearChunkStream(msgId: msgId);

/// แปลง wire tag (1–4) เป็น [PayloadTagDto]
PayloadTagDto? payloadTagFromU8({required int value}) =>
    ResilNetCore.instance.api.crateApiRouterApiPayloadTagFromU8(value: value);
