// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/dto.dart';
import 'api/nostr_api.dart';
import 'api/router_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class ResilNetCoreApiImplPlatform
    extends BaseApiImpl<ResilNetCoreWire> {
  ResilNetCoreApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<GeoNoticeDto> dco_decode_StreamSink_geo_notice_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<GeoPresenceDto> dco_decode_StreamSink_geo_presence_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<MessagePacketDto> dco_decode_StreamSink_message_packet_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MessagePacketDto dco_decode_box_autoadd_message_packet_dto(dynamic raw);

  @protected
  PayloadTagDto dco_decode_box_autoadd_payload_tag_dto(dynamic raw);

  @protected
  ResilNetEnvelopeDto dco_decode_box_autoadd_resil_net_envelope_dto(
    dynamic raw,
  );

  @protected
  RouterConfigDto dco_decode_box_autoadd_router_config_dto(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  GeoNoticeDto dco_decode_geo_notice_dto(dynamic raw);

  @protected
  GeoPresenceDto dco_decode_geo_presence_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<GeoNoticeDto> dco_decode_list_geo_notice_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RelayStatusDto> dco_decode_list_relay_status_dto(dynamic raw);

  @protected
  List<TransportTypeDto> dco_decode_list_transport_type_dto(dynamic raw);

  @protected
  MessagePacketDto dco_decode_message_packet_dto(dynamic raw);

  @protected
  NetworkStatusDto dco_decode_network_status_dto(dynamic raw);

  @protected
  NostrInitResultDto dco_decode_nostr_init_result_dto(dynamic raw);

  @protected
  NostrPoolStatusDto dco_decode_nostr_pool_status_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PayloadTagDto? dco_decode_opt_box_autoadd_payload_tag_dto(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PayloadTagDto dco_decode_payload_tag_dto(dynamic raw);

  @protected
  RelayStatusDto dco_decode_relay_status_dto(dynamic raw);

  @protected
  ResilNetEnvelopeDto dco_decode_resil_net_envelope_dto(dynamic raw);

  @protected
  RoutedPacketDto dco_decode_routed_packet_dto(dynamic raw);

  @protected
  RouterConfigDto dco_decode_router_config_dto(dynamic raw);

  @protected
  TransportTypeDto dco_decode_transport_type_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<GeoNoticeDto> sse_decode_StreamSink_geo_notice_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<GeoPresenceDto> sse_decode_StreamSink_geo_presence_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MessagePacketDto> sse_decode_StreamSink_message_packet_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MessagePacketDto sse_decode_box_autoadd_message_packet_dto(
    SseDeserializer deserializer,
  );

  @protected
  PayloadTagDto sse_decode_box_autoadd_payload_tag_dto(
    SseDeserializer deserializer,
  );

  @protected
  ResilNetEnvelopeDto sse_decode_box_autoadd_resil_net_envelope_dto(
    SseDeserializer deserializer,
  );

  @protected
  RouterConfigDto sse_decode_box_autoadd_router_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  GeoNoticeDto sse_decode_geo_notice_dto(SseDeserializer deserializer);

  @protected
  GeoPresenceDto sse_decode_geo_presence_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<GeoNoticeDto> sse_decode_list_geo_notice_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RelayStatusDto> sse_decode_list_relay_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TransportTypeDto> sse_decode_list_transport_type_dto(
    SseDeserializer deserializer,
  );

  @protected
  MessagePacketDto sse_decode_message_packet_dto(SseDeserializer deserializer);

  @protected
  NetworkStatusDto sse_decode_network_status_dto(SseDeserializer deserializer);

  @protected
  NostrInitResultDto sse_decode_nostr_init_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  NostrPoolStatusDto sse_decode_nostr_pool_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PayloadTagDto? sse_decode_opt_box_autoadd_payload_tag_dto(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PayloadTagDto sse_decode_payload_tag_dto(SseDeserializer deserializer);

  @protected
  RelayStatusDto sse_decode_relay_status_dto(SseDeserializer deserializer);

  @protected
  ResilNetEnvelopeDto sse_decode_resil_net_envelope_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoutedPacketDto sse_decode_routed_packet_dto(SseDeserializer deserializer);

  @protected
  RouterConfigDto sse_decode_router_config_dto(SseDeserializer deserializer);

  @protected
  TransportTypeDto sse_decode_transport_type_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_geo_notice_dto_Sse(
    RustStreamSink<GeoNoticeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_geo_presence_dto_Sse(
    RustStreamSink<GeoPresenceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_message_packet_dto_Sse(
    RustStreamSink<MessagePacketDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_packet_dto(
    MessagePacketDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_payload_tag_dto(
    PayloadTagDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resil_net_envelope_dto(
    ResilNetEnvelopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_router_config_dto(
    RouterConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_geo_notice_dto(GeoNoticeDto self, SseSerializer serializer);

  @protected
  void sse_encode_geo_presence_dto(
    GeoPresenceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_geo_notice_dto(
    List<GeoNoticeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relay_status_dto(
    List<RelayStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transport_type_dto(
    List<TransportTypeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_packet_dto(
    MessagePacketDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_status_dto(
    NetworkStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_init_result_dto(
    NostrInitResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_pool_status_dto(
    NostrPoolStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_payload_tag_dto(
    PayloadTagDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_payload_tag_dto(PayloadTagDto self, SseSerializer serializer);

  @protected
  void sse_encode_relay_status_dto(
    RelayStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resil_net_envelope_dto(
    ResilNetEnvelopeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_routed_packet_dto(
    RoutedPacketDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_router_config_dto(
    RouterConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_type_dto(
    TransportTypeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class ResilNetCoreWire implements BaseWire {
  ResilNetCoreWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external ResilNetCoreWasmModule get wasmModule;

@JS()
@anonymous
extension type ResilNetCoreWasmModule._(JSObject _) implements JSObject {}
