// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dto.dart';
import 'api/router_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class ResilNetCore
    extends
        BaseEntrypoint<ResilNetCoreApi, ResilNetCoreApiImpl, ResilNetCoreWire> {
  @internal
  static final instance = ResilNetCore._();

  ResilNetCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    ResilNetCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required ResilNetCoreApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<ResilNetCoreApiImpl, ResilNetCoreWire>
  get apiImplConstructor => ResilNetCoreApiImpl.new;

  @override
  WireConstructor<ResilNetCoreWire> get wireConstructor =>
      ResilNetCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiRouterApiInitResilnetCore();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 991158679;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'resilnet_core',
        ioDirectory: '../resilnet_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class ResilNetCoreApi extends BaseApi {
  bool crateApiRouterApiCheckChunkDedup({
    required int msgId,
    required int chunkIndex,
  });

  void crateApiRouterApiClearChunkStream({required int msgId});

  Future<NetworkStatusDto> crateApiRouterApiGetNetworkStatus();

  Future<void> crateApiRouterApiIngestPacket({
    required MessagePacketDto packet,
  });

  Future<void> crateApiRouterApiInitResilnetCore();

  Future<void> crateApiRouterApiInitRouter({required RouterConfigDto config});

  bool crateApiRouterApiIsRouterInitialized();

  Future<int> crateApiRouterApiOfflineQueueLen();

  PayloadTagDto? crateApiRouterApiPayloadTagFromU8({required int value});

  Future<RoutedPacketDto> crateApiRouterApiRoutePacket({
    required MessagePacketDto packet,
  });

  Stream<MessagePacketDto> crateApiRouterApiSubscribeIncomingMessages();

  Future<void> crateApiRouterApiUpdateNetworkStatus({
    required bool isInternetAvailable,
    required int activeBlePeersCount,
  });
}

class ResilNetCoreApiImpl extends ResilNetCoreApiImplPlatform
    implements ResilNetCoreApi {
  ResilNetCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiRouterApiCheckChunkDedup({
    required int msgId,
    required int chunkIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(msgId, serializer);
          sse_encode_u_8(chunkIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRouterApiCheckChunkDedupConstMeta,
        argValues: [msgId, chunkIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiCheckChunkDedupConstMeta =>
      const TaskConstMeta(
        debugName: "check_chunk_dedup",
        argNames: ["msgId", "chunkIndex"],
      );

  @override
  void crateApiRouterApiClearChunkStream({required int msgId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(msgId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiClearChunkStreamConstMeta,
        argValues: [msgId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiClearChunkStreamConstMeta =>
      const TaskConstMeta(debugName: "clear_chunk_stream", argNames: ["msgId"]);

  @override
  Future<NetworkStatusDto> crateApiRouterApiGetNetworkStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_status_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiGetNetworkStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiGetNetworkStatusConstMeta =>
      const TaskConstMeta(debugName: "get_network_status", argNames: []);

  @override
  Future<void> crateApiRouterApiIngestPacket({
    required MessagePacketDto packet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_message_packet_dto(packet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiIngestPacketConstMeta,
        argValues: [packet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiIngestPacketConstMeta =>
      const TaskConstMeta(debugName: "ingest_packet", argNames: ["packet"]);

  @override
  Future<void> crateApiRouterApiInitResilnetCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRouterApiInitResilnetCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiInitResilnetCoreConstMeta =>
      const TaskConstMeta(debugName: "init_resilnet_core", argNames: []);

  @override
  Future<void> crateApiRouterApiInitRouter({required RouterConfigDto config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_router_config_dto(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiInitRouterConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiInitRouterConstMeta =>
      const TaskConstMeta(debugName: "init_router", argNames: ["config"]);

  @override
  bool crateApiRouterApiIsRouterInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRouterApiIsRouterInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiIsRouterInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_router_initialized", argNames: []);

  @override
  Future<int> crateApiRouterApiOfflineQueueLen() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiOfflineQueueLenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiOfflineQueueLenConstMeta =>
      const TaskConstMeta(debugName: "offline_queue_len", argNames: []);

  @override
  PayloadTagDto? crateApiRouterApiPayloadTagFromU8({required int value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_payload_tag_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRouterApiPayloadTagFromU8ConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiPayloadTagFromU8ConstMeta =>
      const TaskConstMeta(
        debugName: "payload_tag_from_u8",
        argNames: ["value"],
      );

  @override
  Future<RoutedPacketDto> crateApiRouterApiRoutePacket({
    required MessagePacketDto packet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_message_packet_dto(packet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_routed_packet_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiRoutePacketConstMeta,
        argValues: [packet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiRoutePacketConstMeta =>
      const TaskConstMeta(debugName: "route_packet", argNames: ["packet"]);

  @override
  Stream<MessagePacketDto> crateApiRouterApiSubscribeIncomingMessages() {
    final sink = RustStreamSink<MessagePacketDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_message_packet_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiRouterApiSubscribeIncomingMessagesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRouterApiSubscribeIncomingMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_incoming_messages",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiRouterApiUpdateNetworkStatus({
    required bool isInternetAvailable,
    required int activeBlePeersCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(isInternetAvailable, serializer);
          sse_encode_u_32(activeBlePeersCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRouterApiUpdateNetworkStatusConstMeta,
        argValues: [isInternetAvailable, activeBlePeersCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRouterApiUpdateNetworkStatusConstMeta =>
      const TaskConstMeta(
        debugName: "update_network_status",
        argNames: ["isInternetAvailable", "activeBlePeersCount"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<MessagePacketDto> dco_decode_StreamSink_message_packet_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MessagePacketDto dco_decode_box_autoadd_message_packet_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message_packet_dto(raw);
  }

  @protected
  PayloadTagDto dco_decode_box_autoadd_payload_tag_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_payload_tag_dto(raw);
  }

  @protected
  RouterConfigDto dco_decode_box_autoadd_router_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_router_config_dto(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessagePacketDto dco_decode_message_packet_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MessagePacketDto(
      id: dco_decode_String(arr[0]),
      sender: dco_decode_String(arr[1]),
      receiver: dco_decode_String(arr[2]),
      payload: dco_decode_list_prim_u_8_strict(arr[3]),
      timestamp: dco_decode_u_64(arr[4]),
      ttl: dco_decode_u_8(arr[5]),
      payloadTag: dco_decode_payload_tag_dto(arr[6]),
    );
  }

  @protected
  NetworkStatusDto dco_decode_network_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NetworkStatusDto(
      isInternetAvailable: dco_decode_bool(arr[0]),
      activeBlePeersCount: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  PayloadTagDto? dco_decode_opt_box_autoadd_payload_tag_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_payload_tag_dto(raw);
  }

  @protected
  PayloadTagDto dco_decode_payload_tag_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PayloadTagDto.values[raw as int];
  }

  @protected
  RoutedPacketDto dco_decode_routed_packet_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RoutedPacketDto(
      transport: dco_decode_transport_type_dto(arr[0]),
      packet: dco_decode_message_packet_dto(arr[1]),
    );
  }

  @protected
  RouterConfigDto dco_decode_router_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RouterConfigDto(
      dedupCapacity: dco_decode_u_32(arr[0]),
      dedupTtlSecs: dco_decode_u_64(arr[1]),
      internetTtlReset: dco_decode_u_8(arr[2]),
      offlineQueueCapacity: dco_decode_u_32(arr[3]),
      eventChannelCapacity: dco_decode_u_32(arr[4]),
      incomingChannelCapacity: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  TransportTypeDto dco_decode_transport_type_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransportTypeDto.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<MessagePacketDto> sse_decode_StreamSink_message_packet_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MessagePacketDto sse_decode_box_autoadd_message_packet_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message_packet_dto(deserializer));
  }

  @protected
  PayloadTagDto sse_decode_box_autoadd_payload_tag_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_payload_tag_dto(deserializer));
  }

  @protected
  RouterConfigDto sse_decode_box_autoadd_router_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_router_config_dto(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessagePacketDto sse_decode_message_packet_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_receiver = sse_decode_String(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_ttl = sse_decode_u_8(deserializer);
    var var_payloadTag = sse_decode_payload_tag_dto(deserializer);
    return MessagePacketDto(
      id: var_id,
      sender: var_sender,
      receiver: var_receiver,
      payload: var_payload,
      timestamp: var_timestamp,
      ttl: var_ttl,
      payloadTag: var_payloadTag,
    );
  }

  @protected
  NetworkStatusDto sse_decode_network_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isInternetAvailable = sse_decode_bool(deserializer);
    var var_activeBlePeersCount = sse_decode_u_32(deserializer);
    return NetworkStatusDto(
      isInternetAvailable: var_isInternetAvailable,
      activeBlePeersCount: var_activeBlePeersCount,
    );
  }

  @protected
  PayloadTagDto? sse_decode_opt_box_autoadd_payload_tag_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_payload_tag_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PayloadTagDto sse_decode_payload_tag_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PayloadTagDto.values[inner];
  }

  @protected
  RoutedPacketDto sse_decode_routed_packet_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transport = sse_decode_transport_type_dto(deserializer);
    var var_packet = sse_decode_message_packet_dto(deserializer);
    return RoutedPacketDto(transport: var_transport, packet: var_packet);
  }

  @protected
  RouterConfigDto sse_decode_router_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dedupCapacity = sse_decode_u_32(deserializer);
    var var_dedupTtlSecs = sse_decode_u_64(deserializer);
    var var_internetTtlReset = sse_decode_u_8(deserializer);
    var var_offlineQueueCapacity = sse_decode_u_32(deserializer);
    var var_eventChannelCapacity = sse_decode_u_32(deserializer);
    var var_incomingChannelCapacity = sse_decode_u_32(deserializer);
    return RouterConfigDto(
      dedupCapacity: var_dedupCapacity,
      dedupTtlSecs: var_dedupTtlSecs,
      internetTtlReset: var_internetTtlReset,
      offlineQueueCapacity: var_offlineQueueCapacity,
      eventChannelCapacity: var_eventChannelCapacity,
      incomingChannelCapacity: var_incomingChannelCapacity,
    );
  }

  @protected
  TransportTypeDto sse_decode_transport_type_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransportTypeDto.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_message_packet_dto_Sse(
    RustStreamSink<MessagePacketDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_packet_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_message_packet_dto(
    MessagePacketDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message_packet_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_payload_tag_dto(
    PayloadTagDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_payload_tag_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_router_config_dto(
    RouterConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_router_config_dto(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_packet_dto(
    MessagePacketDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.receiver, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_u_8(self.ttl, serializer);
    sse_encode_payload_tag_dto(self.payloadTag, serializer);
  }

  @protected
  void sse_encode_network_status_dto(
    NetworkStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isInternetAvailable, serializer);
    sse_encode_u_32(self.activeBlePeersCount, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_payload_tag_dto(
    PayloadTagDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_payload_tag_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_payload_tag_dto(
    PayloadTagDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_routed_packet_dto(
    RoutedPacketDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transport_type_dto(self.transport, serializer);
    sse_encode_message_packet_dto(self.packet, serializer);
  }

  @protected
  void sse_encode_router_config_dto(
    RouterConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.dedupCapacity, serializer);
    sse_encode_u_64(self.dedupTtlSecs, serializer);
    sse_encode_u_8(self.internetTtlReset, serializer);
    sse_encode_u_32(self.offlineQueueCapacity, serializer);
    sse_encode_u_32(self.eventChannelCapacity, serializer);
    sse_encode_u_32(self.incomingChannelCapacity, serializer);
  }

  @protected
  void sse_encode_transport_type_dto(
    TransportTypeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
