// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = SseCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 760302760;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__router_api__check_chunk_dedup_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "check_chunk_dedup", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_msg_id = <u16>::sse_decode(&mut deserializer);
let api_chunk_index = <u8>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, ()>((move || {
                     let output_ok = Result::<_,()>::Ok(crate::api::router_api::check_chunk_dedup(api_msg_id, api_chunk_index))?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__router_api__clear_chunk_stream_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "clear_chunk_stream", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_msg_id = <u16>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, String>((move || {
                     let output_ok = crate::api::router_api::clear_chunk_stream(api_msg_id)?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__router_api__clear_offline_queue_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "clear_offline_queue", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::router_api::clear_offline_queue().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__flush_offline_queue_to_nostr_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "flush_offline_queue_to_nostr", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::flush_offline_queue_to_nostr().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__router_api__get_network_status_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_network_status", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::router_api::get_network_status()?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__nostr_api__get_nostr_status_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_nostr_status", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::nostr_api::get_nostr_status()?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__nostr_api__ingest_nostr_envelope_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "ingest_nostr_envelope", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_envelope = <crate::api::dto::ResilNetEnvelopeDto>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::ingest_nostr_envelope(api_envelope).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__router_api__ingest_packet_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "ingest_packet", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_packet = <crate::api::dto::MessagePacketDto>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::router_api::ingest_packet(api_packet).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__init_nostr_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_nostr", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_secret_key_hex = <Option<String>>::sse_decode(&mut deserializer);
let api_relay_urls = <Option<Vec<String>>>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::init_nostr(api_secret_key_hex, api_relay_urls).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__router_api__init_resilnet_core_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_resilnet_core", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::router_api::init_resilnet_core(); })?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__router_api__init_router_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_router", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::dto::RouterConfigDto>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::router_api::init_router(api_config)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__router_api__is_router_initialized_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "is_router_initialized", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, ()>((move || {
                     let output_ok = Result::<_,()>::Ok(crate::api::router_api::is_router_initialized())?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__nostr_api__nostr_publish_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "nostr_publish", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_envelope = <crate::api::dto::ResilNetEnvelopeDto>::sse_decode(&mut deserializer);
let api_kind = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::nostr_publish(api_envelope, api_kind).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__nostr_publish_geo_presence_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "nostr_publish_geo_presence", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_geohash = <String>::sse_decode(&mut deserializer);
let api_nick = <String>::sse_decode(&mut deserializer);
let api_rid = <String>::sse_decode(&mut deserializer);
let api_pk = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::nostr_publish_geo_presence(api_geohash, api_nick, api_rid, api_pk).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__nostr_publish_packet_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "nostr_publish_packet", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_packet = <crate::api::dto::MessagePacketDto>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::nostr_publish_packet(api_packet).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__nostr_reconnect_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "nostr_reconnect", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::nostr_reconnect().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__nostr_set_geo_presence_filter_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "nostr_set_geo_presence_filter", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_geohashes = <Vec<String>>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::nostr_set_geo_presence_filter(api_geohashes).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__nostr_api__nostr_subscribe_geo_presence_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "nostr_subscribe_geo_presence", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<crate::api::dto::GeoPresenceDto,flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::nostr_api::nostr_subscribe_geo_presence(api_sink).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__router_api__offline_queue_len_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "offline_queue_len", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::router_api::offline_queue_len().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__dto__payload_tag_dto_as_u8_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "payload_tag_dto_as_u8", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::dto::PayloadTagDto>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::dto::PayloadTagDto::as_u8(api_that))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__dto__payload_tag_dto_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "payload_tag_dto_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::dto::PayloadTagDto::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__dto__payload_tag_dto_from_u8_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "payload_tag_dto_from_u8", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_value = <u8>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::dto::PayloadTagDto::from_u8(api_value))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__router_api__payload_tag_from_u8_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "payload_tag_from_u8", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_value = <u8>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, ()>((move || {
                     let output_ok = Result::<_,()>::Ok(crate::api::router_api::payload_tag_from_u8(api_value))?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__router_api__route_packet_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "route_packet", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_packet = <crate::api::dto::MessagePacketDto>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::router_api::route_packet(api_packet).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__dto__router_config_dto_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "router_config_dto_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::dto::RouterConfigDto::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__router_api__subscribe_incoming_messages_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "subscribe_incoming_messages", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<crate::api::dto::MessagePacketDto,flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, String>((move || async move {
                         let output_ok = crate::api::router_api::subscribe_incoming_messages(api_sink).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__router_api__update_network_status_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "update_network_status", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_is_internet_available = <bool>::sse_decode(&mut deserializer);
let api_active_ble_peers_count = <u32>::sse_decode(&mut deserializer);
let api_lora_available = <bool>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::router_api::update_network_status(api_is_internet_available, api_active_ble_peers_count, api_lora_available)?;   Ok(output_ok)
                    })())
                } })
            }

// Section: dart2rust


                impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);}
                }
                
                impl SseDecode for StreamSink<crate::api::dto::GeoPresenceDto,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);}
                }
                
                impl SseDecode for StreamSink<crate::api::dto::MessagePacketDto,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);}
                }
                
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for crate::api::dto::GeoPresenceDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_eventId = <String>::sse_decode(deserializer);
let mut var_pubkeyHex = <String>::sse_decode(deserializer);
let mut var_geohash = <String>::sse_decode(deserializer);
let mut var_nick = <String>::sse_decode(deserializer);
let mut var_createdAt = <u64>::sse_decode(deserializer);
let mut var_rid = <String>::sse_decode(deserializer);
let mut var_pk = <String>::sse_decode(deserializer);
return crate::api::dto::GeoPresenceDto{event_id: var_eventId, pubkey_hex: var_pubkeyHex, geohash: var_geohash, nick: var_nick, created_at: var_createdAt, rid: var_rid, pk: var_pk};}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<String>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::dto::RelayStatusDto> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::dto::RelayStatusDto>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::dto::TransportTypeDto> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::dto::TransportTypeDto>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for crate::api::dto::MessagePacketDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_id = <String>::sse_decode(deserializer);
let mut var_sender = <String>::sse_decode(deserializer);
let mut var_receiver = <String>::sse_decode(deserializer);
let mut var_payload = <Vec<u8>>::sse_decode(deserializer);
let mut var_timestamp = <u64>::sse_decode(deserializer);
let mut var_ttl = <u8>::sse_decode(deserializer);
let mut var_payloadTag = <crate::api::dto::PayloadTagDto>::sse_decode(deserializer);
return crate::api::dto::MessagePacketDto{id: var_id, sender: var_sender, receiver: var_receiver, payload: var_payload, timestamp: var_timestamp, ttl: var_ttl, payload_tag: var_payloadTag};}
                }
                
                impl SseDecode for crate::api::dto::NetworkStatusDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_isInternetAvailable = <bool>::sse_decode(deserializer);
let mut var_activeBlePeersCount = <u32>::sse_decode(deserializer);
let mut var_loraAvailable = <bool>::sse_decode(deserializer);
return crate::api::dto::NetworkStatusDto{is_internet_available: var_isInternetAvailable, active_ble_peers_count: var_activeBlePeersCount, lora_available: var_loraAvailable};}
                }
                
                impl SseDecode for crate::api::dto::NostrInitResultDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_status = <crate::api::dto::NostrPoolStatusDto>::sse_decode(deserializer);
let mut var_secretKeyHex = <String>::sse_decode(deserializer);
return crate::api::dto::NostrInitResultDto{status: var_status, secret_key_hex: var_secretKeyHex};}
                }
                
                impl SseDecode for crate::api::dto::NostrPoolStatusDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_initialized = <bool>::sse_decode(deserializer);
let mut var_pubkeyHex = <String>::sse_decode(deserializer);
let mut var_npub = <String>::sse_decode(deserializer);
let mut var_connectedRelays = <u32>::sse_decode(deserializer);
let mut var_totalRelays = <u32>::sse_decode(deserializer);
let mut var_relays = <Vec<crate::api::dto::RelayStatusDto>>::sse_decode(deserializer);
return crate::api::dto::NostrPoolStatusDto{initialized: var_initialized, pubkey_hex: var_pubkeyHex, npub: var_npub, connected_relays: var_connectedRelays, total_relays: var_totalRelays, relays: var_relays};}
                }
                
                impl SseDecode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<String>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for Option<crate::api::dto::PayloadTagDto> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<crate::api::dto::PayloadTagDto>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for Option<Vec<String>> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<Vec<String>>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for crate::api::dto::PayloadTagDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::dto::PayloadTagDto::Text,
1 => crate::api::dto::PayloadTagDto::Image,
2 => crate::api::dto::PayloadTagDto::Audio,
3 => crate::api::dto::PayloadTagDto::Firmware,
4 => crate::api::dto::PayloadTagDto::Ack,
            _ => unreachable!("Invalid variant for PayloadTagDto: {}", inner),
        };}
                }
                
                impl SseDecode for crate::api::dto::RelayStatusDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_url = <String>::sse_decode(deserializer);
let mut var_connected = <bool>::sse_decode(deserializer);
return crate::api::dto::RelayStatusDto{url: var_url, connected: var_connected};}
                }
                
                impl SseDecode for crate::api::dto::ResilNetEnvelopeDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_id = <String>::sse_decode(deserializer);
let mut var_sender = <String>::sse_decode(deserializer);
let mut var_receiver = <String>::sse_decode(deserializer);
let mut var_payloadB64 = <String>::sse_decode(deserializer);
let mut var_timestamp = <u64>::sse_decode(deserializer);
let mut var_ttl = <u8>::sse_decode(deserializer);
let mut var_payloadTag = <u8>::sse_decode(deserializer);
let mut var_kind = <String>::sse_decode(deserializer);
return crate::api::dto::ResilNetEnvelopeDto{id: var_id, sender: var_sender, receiver: var_receiver, payload_b64: var_payloadB64, timestamp: var_timestamp, ttl: var_ttl, payload_tag: var_payloadTag, kind: var_kind};}
                }
                
                impl SseDecode for crate::api::dto::RoutedPacketDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_transport = <crate::api::dto::TransportTypeDto>::sse_decode(deserializer);
let mut var_transports = <Vec<crate::api::dto::TransportTypeDto>>::sse_decode(deserializer);
let mut var_packet = <crate::api::dto::MessagePacketDto>::sse_decode(deserializer);
return crate::api::dto::RoutedPacketDto{transport: var_transport, transports: var_transports, packet: var_packet};}
                }
                
                impl SseDecode for crate::api::dto::RouterConfigDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_dedupCapacity = <u32>::sse_decode(deserializer);
let mut var_dedupTtlSecs = <u64>::sse_decode(deserializer);
let mut var_internetTtlReset = <u8>::sse_decode(deserializer);
let mut var_offlineQueueCapacity = <u32>::sse_decode(deserializer);
let mut var_eventChannelCapacity = <u32>::sse_decode(deserializer);
let mut var_incomingChannelCapacity = <u32>::sse_decode(deserializer);
return crate::api::dto::RouterConfigDto{dedup_capacity: var_dedupCapacity, dedup_ttl_secs: var_dedupTtlSecs, internet_ttl_reset: var_internetTtlReset, offline_queue_capacity: var_offlineQueueCapacity, event_channel_capacity: var_eventChannelCapacity, incoming_channel_capacity: var_incomingChannelCapacity};}
                }
                
                impl SseDecode for crate::api::dto::TransportTypeDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::dto::TransportTypeDto::Nostr,
1 => crate::api::dto::TransportTypeDto::BluetoothMesh,
2 => crate::api::dto::TransportTypeDto::LoRa,
3 => crate::api::dto::TransportTypeDto::OfflineQueue,
            _ => unreachable!("Invalid variant for TransportTypeDto: {}", inner),
        };}
                }
                
                impl SseDecode for u16 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u16::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        3 => wire__crate__api__router_api__clear_offline_queue_impl(port, ptr, rust_vec_len, data_len),
4 => wire__crate__api__nostr_api__flush_offline_queue_to_nostr_impl(port, ptr, rust_vec_len, data_len),
5 => wire__crate__api__router_api__get_network_status_impl(port, ptr, rust_vec_len, data_len),
6 => wire__crate__api__nostr_api__get_nostr_status_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__api__nostr_api__ingest_nostr_envelope_impl(port, ptr, rust_vec_len, data_len),
8 => wire__crate__api__router_api__ingest_packet_impl(port, ptr, rust_vec_len, data_len),
9 => wire__crate__api__nostr_api__init_nostr_impl(port, ptr, rust_vec_len, data_len),
10 => wire__crate__api__router_api__init_resilnet_core_impl(port, ptr, rust_vec_len, data_len),
11 => wire__crate__api__router_api__init_router_impl(port, ptr, rust_vec_len, data_len),
13 => wire__crate__api__nostr_api__nostr_publish_impl(port, ptr, rust_vec_len, data_len),
14 => wire__crate__api__nostr_api__nostr_publish_geo_presence_impl(port, ptr, rust_vec_len, data_len),
15 => wire__crate__api__nostr_api__nostr_publish_packet_impl(port, ptr, rust_vec_len, data_len),
16 => wire__crate__api__nostr_api__nostr_reconnect_impl(port, ptr, rust_vec_len, data_len),
17 => wire__crate__api__nostr_api__nostr_set_geo_presence_filter_impl(port, ptr, rust_vec_len, data_len),
18 => wire__crate__api__nostr_api__nostr_subscribe_geo_presence_impl(port, ptr, rust_vec_len, data_len),
19 => wire__crate__api__router_api__offline_queue_len_impl(port, ptr, rust_vec_len, data_len),
20 => wire__crate__api__dto__payload_tag_dto_as_u8_impl(port, ptr, rust_vec_len, data_len),
21 => wire__crate__api__dto__payload_tag_dto_default_impl(port, ptr, rust_vec_len, data_len),
22 => wire__crate__api__dto__payload_tag_dto_from_u8_impl(port, ptr, rust_vec_len, data_len),
24 => wire__crate__api__router_api__route_packet_impl(port, ptr, rust_vec_len, data_len),
25 => wire__crate__api__dto__router_config_dto_default_impl(port, ptr, rust_vec_len, data_len),
26 => wire__crate__api__router_api__subscribe_incoming_messages_impl(port, ptr, rust_vec_len, data_len),
27 => wire__crate__api__router_api__update_network_status_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__api__router_api__check_chunk_dedup_impl(ptr, rust_vec_len, data_len),
2 => wire__crate__api__router_api__clear_chunk_stream_impl(ptr, rust_vec_len, data_len),
12 => wire__crate__api__router_api__is_router_initialized_impl(ptr, rust_vec_len, data_len),
23 => wire__crate__api__router_api__payload_tag_from_u8_impl(ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::GeoPresenceDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.event_id.into_into_dart().into_dart(),
self.pubkey_hex.into_into_dart().into_dart(),
self.geohash.into_into_dart().into_dart(),
self.nick.into_into_dart().into_dart(),
self.created_at.into_into_dart().into_dart(),
self.rid.into_into_dart().into_dart(),
self.pk.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::GeoPresenceDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::GeoPresenceDto> for crate::api::dto::GeoPresenceDto {
            fn into_into_dart(self) -> crate::api::dto::GeoPresenceDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::MessagePacketDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.id.into_into_dart().into_dart(),
self.sender.into_into_dart().into_dart(),
self.receiver.into_into_dart().into_dart(),
self.payload.into_into_dart().into_dart(),
self.timestamp.into_into_dart().into_dart(),
self.ttl.into_into_dart().into_dart(),
self.payload_tag.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::MessagePacketDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::MessagePacketDto> for crate::api::dto::MessagePacketDto {
            fn into_into_dart(self) -> crate::api::dto::MessagePacketDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::NetworkStatusDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.is_internet_available.into_into_dart().into_dart(),
self.active_ble_peers_count.into_into_dart().into_dart(),
self.lora_available.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::NetworkStatusDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::NetworkStatusDto> for crate::api::dto::NetworkStatusDto {
            fn into_into_dart(self) -> crate::api::dto::NetworkStatusDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::NostrInitResultDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.status.into_into_dart().into_dart(),
self.secret_key_hex.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::NostrInitResultDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::NostrInitResultDto> for crate::api::dto::NostrInitResultDto {
            fn into_into_dart(self) -> crate::api::dto::NostrInitResultDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::NostrPoolStatusDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.initialized.into_into_dart().into_dart(),
self.pubkey_hex.into_into_dart().into_dart(),
self.npub.into_into_dart().into_dart(),
self.connected_relays.into_into_dart().into_dart(),
self.total_relays.into_into_dart().into_dart(),
self.relays.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::NostrPoolStatusDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::NostrPoolStatusDto> for crate::api::dto::NostrPoolStatusDto {
            fn into_into_dart(self) -> crate::api::dto::NostrPoolStatusDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::PayloadTagDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Text => 0.into_dart(),
Self::Image => 1.into_dart(),
Self::Audio => 2.into_dart(),
Self::Firmware => 3.into_dart(),
Self::Ack => 4.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::PayloadTagDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::PayloadTagDto> for crate::api::dto::PayloadTagDto {
            fn into_into_dart(self) -> crate::api::dto::PayloadTagDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::RelayStatusDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.url.into_into_dart().into_dart(),
self.connected.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::RelayStatusDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::RelayStatusDto> for crate::api::dto::RelayStatusDto {
            fn into_into_dart(self) -> crate::api::dto::RelayStatusDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::ResilNetEnvelopeDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.id.into_into_dart().into_dart(),
self.sender.into_into_dart().into_dart(),
self.receiver.into_into_dart().into_dart(),
self.payload_b64.into_into_dart().into_dart(),
self.timestamp.into_into_dart().into_dart(),
self.ttl.into_into_dart().into_dart(),
self.payload_tag.into_into_dart().into_dart(),
self.kind.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::ResilNetEnvelopeDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::ResilNetEnvelopeDto> for crate::api::dto::ResilNetEnvelopeDto {
            fn into_into_dart(self) -> crate::api::dto::ResilNetEnvelopeDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::RoutedPacketDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.transport.into_into_dart().into_dart(),
self.transports.into_into_dart().into_dart(),
self.packet.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::RoutedPacketDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::RoutedPacketDto> for crate::api::dto::RoutedPacketDto {
            fn into_into_dart(self) -> crate::api::dto::RoutedPacketDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::RouterConfigDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.dedup_capacity.into_into_dart().into_dart(),
self.dedup_ttl_secs.into_into_dart().into_dart(),
self.internet_ttl_reset.into_into_dart().into_dart(),
self.offline_queue_capacity.into_into_dart().into_dart(),
self.event_channel_capacity.into_into_dart().into_dart(),
self.incoming_channel_capacity.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::RouterConfigDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::RouterConfigDto> for crate::api::dto::RouterConfigDto {
            fn into_into_dart(self) -> crate::api::dto::RouterConfigDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::dto::TransportTypeDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Nostr => 0.into_dart(),
Self::BluetoothMesh => 1.into_dart(),
Self::LoRa => 2.into_dart(),
Self::OfflineQueue => 3.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::dto::TransportTypeDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dto::TransportTypeDto> for crate::api::dto::TransportTypeDto {
            fn into_into_dart(self) -> crate::api::dto::TransportTypeDto {
                self
            }
        }

                impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(format!("{:?}", self), serializer);}
                }
                
                impl SseEncode for StreamSink<crate::api::dto::GeoPresenceDto,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {unimplemented!("")}
                }
                
                impl SseEncode for StreamSink<crate::api::dto::MessagePacketDto,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {unimplemented!("")}
                }
                
                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for crate::api::dto::GeoPresenceDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.event_id, serializer);
<String>::sse_encode(self.pubkey_hex, serializer);
<String>::sse_encode(self.geohash, serializer);
<String>::sse_encode(self.nick, serializer);
<u64>::sse_encode(self.created_at, serializer);
<String>::sse_encode(self.rid, serializer);
<String>::sse_encode(self.pk, serializer);}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <String>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::dto::RelayStatusDto> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::dto::RelayStatusDto>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::dto::TransportTypeDto> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::dto::TransportTypeDto>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for crate::api::dto::MessagePacketDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.id, serializer);
<String>::sse_encode(self.sender, serializer);
<String>::sse_encode(self.receiver, serializer);
<Vec<u8>>::sse_encode(self.payload, serializer);
<u64>::sse_encode(self.timestamp, serializer);
<u8>::sse_encode(self.ttl, serializer);
<crate::api::dto::PayloadTagDto>::sse_encode(self.payload_tag, serializer);}
                }
                
                impl SseEncode for crate::api::dto::NetworkStatusDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_internet_available, serializer);
<u32>::sse_encode(self.active_ble_peers_count, serializer);
<bool>::sse_encode(self.lora_available, serializer);}
                }
                
                impl SseEncode for crate::api::dto::NostrInitResultDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::api::dto::NostrPoolStatusDto>::sse_encode(self.status, serializer);
<String>::sse_encode(self.secret_key_hex, serializer);}
                }
                
                impl SseEncode for crate::api::dto::NostrPoolStatusDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.initialized, serializer);
<String>::sse_encode(self.pubkey_hex, serializer);
<String>::sse_encode(self.npub, serializer);
<u32>::sse_encode(self.connected_relays, serializer);
<u32>::sse_encode(self.total_relays, serializer);
<Vec<crate::api::dto::RelayStatusDto>>::sse_encode(self.relays, serializer);}
                }
                
                impl SseEncode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <String>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for Option<crate::api::dto::PayloadTagDto> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <crate::api::dto::PayloadTagDto>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for Option<Vec<String>> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <Vec<String>>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for crate::api::dto::PayloadTagDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::api::dto::PayloadTagDto::Text => { 0 }
crate::api::dto::PayloadTagDto::Image => { 1 }
crate::api::dto::PayloadTagDto::Audio => { 2 }
crate::api::dto::PayloadTagDto::Firmware => { 3 }
crate::api::dto::PayloadTagDto::Ack => { 4 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::api::dto::RelayStatusDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.url, serializer);
<bool>::sse_encode(self.connected, serializer);}
                }
                
                impl SseEncode for crate::api::dto::ResilNetEnvelopeDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.id, serializer);
<String>::sse_encode(self.sender, serializer);
<String>::sse_encode(self.receiver, serializer);
<String>::sse_encode(self.payload_b64, serializer);
<u64>::sse_encode(self.timestamp, serializer);
<u8>::sse_encode(self.ttl, serializer);
<u8>::sse_encode(self.payload_tag, serializer);
<String>::sse_encode(self.kind, serializer);}
                }
                
                impl SseEncode for crate::api::dto::RoutedPacketDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::api::dto::TransportTypeDto>::sse_encode(self.transport, serializer);
<Vec<crate::api::dto::TransportTypeDto>>::sse_encode(self.transports, serializer);
<crate::api::dto::MessagePacketDto>::sse_encode(self.packet, serializer);}
                }
                
                impl SseEncode for crate::api::dto::RouterConfigDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<u32>::sse_encode(self.dedup_capacity, serializer);
<u64>::sse_encode(self.dedup_ttl_secs, serializer);
<u8>::sse_encode(self.internet_ttl_reset, serializer);
<u32>::sse_encode(self.offline_queue_capacity, serializer);
<u32>::sse_encode(self.event_channel_capacity, serializer);
<u32>::sse_encode(self.incoming_channel_capacity, serializer);}
                }
                
                impl SseEncode for crate::api::dto::TransportTypeDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::api::dto::TransportTypeDto::Nostr => { 0 }
crate::api::dto::TransportTypeDto::BluetoothMesh => { 1 }
crate::api::dto::TransportTypeDto::LoRa => { 2 }
crate::api::dto::TransportTypeDto::OfflineQueue => { 3 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for u16 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u16::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();


        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        